project_id = "slnjliheyiiummxhrgmk"

[api]
enabled = true
port = 54321
schemas = ["public", "storage"]

[db]
port = 54322

[studio]
enabled = true
port = 54323

[[functions]]
name = "user-data-management"
verify_jwt = true

[[functions]]
name = "cdn-config"
verify_jwt = true