project_id = "slnjliheyiiummxhrgmk"

[api]
enabled = true
port = 54321
schemas = ["public", "storage"]

[db]
port = 54322

[studio]
enabled = true
port = 54323

[[functions]]
[functions.user-data-management]
verify_jwt = true

[[functions]]
[functions.cdn-config]
verify_jwt = true