name: Clipt CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Build app
        run: npm run build
        env:
          VITE_SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          VITE_SUPABASE_ANON_KEY: ${{ secrets.SUPABASE_ANON_KEY }}
          
      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-files
          path: dist/
          
  deploy:
    needs: build
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    
    steps:
      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: build-files
          path: dist
          
      - name: Deploy to production
        # Add your preferred deployment method here
        # For example, deploy to GitHub Pages:
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          
  sync-supabase-types:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          
      - name: Install Supabase CLI
        run: npm install -g supabase
        
      - name: Generate types
        run: |
          supabase login ${{ secrets.SUPABASE_ACCESS_TOKEN }}
          supabase gen types typescript --project-id slnjliheyiiummxhrgmk > src/integrations/supabase/types.ts
          
      - name: Commit and push type changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore: update Supabase types"
          file_pattern: src/integrations/supabase/types.ts
