// Direct re-exports of lucide icons to prevent circular dependencies
import * as LucideIcons from 'lucide-react';

// Re-export all icons directly without any wrapping
export const {
  Heart: HeartIcon,
  MessageCircle: MessageCircleIcon,
  MessageSquare: MessageIcon,
  Trophy: TrophyIcon,
  Camera: CameraIcon,
  UserPlus: UserPlusIcon,
  UserCheck: UserCheckIcon,
  X: CloseIcon,
  Home: HomeIcon,
  Search: SearchIcon,
  Bell: BellIcon,
  Upload: UploadIcon,
  User: UserIcon,
  Settings: SettingsIcon,
  Video: VideoIcon,
  Award: AwardIcon,
  Monitor: MonitorIcon,
  TrendingUp: TrendingUpIcon,
  Bookmark: BookmarkIcon,
  Check: CheckIcon,
  CheckCheck: CheckCheckIcon,
  ChevronDown: ChevronDownIcon,
  ChevronUp: ChevronUpIcon,
  ChevronLeft: ChevronLeftIcon,
  ChevronRight: ChevronRightIcon,
  Clock: ClockIcon,
  Calendar: CalendarIcon,
  Menu: MenuIcon,
  Mail: MailIcon,
  Send: SendIcon,
  Paperclip: PaperclipIcon,
  MoreVertical: MoreVerticalIcon,
  Edit: EditIcon,
  Trash: TrashIcon,
  ThumbsUp: ThumbsUpIcon,
  Share: ShareIcon,
  Copy: CopyIcon,
  Download: DownloadIcon,
  Flag: FlagIcon,
  Lock: LockIcon,
  Unlock: UnlockIcon,
  Shield: ShieldIcon,
  AlertCircle: AlertCircleIcon,
  HelpCircle: HelpCircleIcon,
  ArrowRight: ArrowRightIcon,
  ArrowLeft: ArrowLeftIcon,
  Power: PowerIcon,
  Moon: MoonIcon,
  Sun: SunIcon,
  Zap: ZapIcon,
  Star: StarIcon
} = LucideIcons;

// Also add an alias for MoreIcon
export const MoreIcon = MoreVerticalIcon;
